### ISSUE TITLE
CSS parser breaks CSS grid layout

### ISSUE THREAD

**Issue by mgetzbw** [forcedotcom/aura#120]
```css
.grid {
  grid-template-columns: [col1-start] 1fr [col1-end col2-start] 1fr [col2-end];
}
```

This syntax breaks the CSS parser, it fails asking if there is a missing semi-colon even though the syntax is standard and supported by all browsers except IE11 and Edge.
